### ISSUE TITLE
1

### ISSUE THREAD

**Issue by ghost** [KID-1912/tiptap-extension-resizable#1]

**Comment by yoruxyy** [comment]
There is something wrong with the upper left and right corners
The upper left corner and upper right corner cannot be dragged.
The lower left corner and lower right corner are normal

**Comment by yoruxyy** [comment]
https://github.com/KID-1912/tiptap-extension-resizable/assets/152286941/6c73bfc3-c92b-4819-a93a-0b3fda2793ba

**Comment by yoruxyy** [comment]
When exporting rich text content to HTML rendering, the image editing size format
